### ISSUE TITLE
npm start 

### ISSUE THREAD

**Issue by EngElham** [jsphkhan/ReactNativeExamples#1]
when i run : npm start an error shows up 

Failed at the weatheapp@0.0.1 start script 'node_modules/react-native/packager/packager.sh'.

i run this command befor npm start : 
npm install babel-core babel-loader babel-plugin-add-module-exports babel-plugin-react-transform babel-plugin-syntax-class-properties babel-plugin-syntax-decorators babel-plugin-syntax-object-rest-spread babel-plugin-transform-class-properties babel-plugin-transform-decorators-legacy babel-plugin-transform-object-rest-spread babel-preset-es2015 babel-preset-react babel-preset-stage-0  React-Native   --save

npm install webpack webpack-dev-server webpack-merge --save

**Comment by jsphkhan** [comment]
This project runs a very old version of React Native which might not be what you have installed. I would suggest copy the code and try in one of your projects and see.
